### ISSUE TITLE
the key check funktion block is broken: >>> ERROR: /home/user/GIT-REPROs/docker-apk-packager/ is not a valid file

### ISSUE THREAD

**Issue by MaxPeal** [hydazz/docker-apk-packager#2]
ser@box:~/GIT-REPROs/docker-apk-packager$ ./build.sh -o ~/GIT-REPROs/docker-apk-packager-OUTPUT-DIR -i /home/user/GIT-REPROs/aports_gitlab.alpinelinux.org_alpine_aports/main/ccache/APKBUILD 
>>> Defaulting version tag to :latest as it is not specified
>>> Defaulting build architecture to x86_64 as it is not specified
>>> ERROR: /home/user/GIT-REPROs/docker-apk-packager/ is not a valid file
user@box:~/GIT-REPROs/docker-apk-packager$

**Comment by hydazz** [comment]
fixed in [d5bb3c2](https://github.com/hydazz/docker-apk-packager/commit/8ce642e52c9b2b9bd193c991ee4a39980f175872). Download the newest build.sh
